apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: "vote.simplon-celia.space"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: votecluster
            port:
              number: 80
